name: Build and Test app

on:
  push:
    branches:
      - main

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node 16
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Run build test
        run: |
          npm install
          npm run build
          npm run test
